### ISSUE TITLE
Do not put connections in dockerfiles

### ISSUE THREAD

**Issue by luizcarlosfaria** [alexandrebeato/bankflix#1]
https://github.com/alexandrebeato/bankflix/blob/94cb24fef555c2254f63b3aff5a46b93ac5c250e/server/Dockerfile#L5

Dockerfiles must be agnostics. 

Use secrets or docker-compose files to set environment variables that represent connectionstrings.

**Comment by alexandrebeato** [comment]
Thanks for the tip.

**Comment by alexandrebeato** [comment]
Solved in [https://github.com/alexandrebeato/bankflix/commit/c2a05924292cd6b0f8c6d9e551269b0cdd37777f](url)
