### ISSUE TITLE
It's not IoC

### ISSUE THREAD

**Issue by luizcarlosfaria** [alexandrebeato/bankflix#2]
https://github.com/alexandrebeato/bankflix/blob/94cb24fef555c2254f63b3aff5a46b93ac5c250e/server/src/Agencia.Infra.CrossCutting/IoC/BootstrapperAgencia.cs#L5

You are defining Dependency Injection, and today, looking your code, this does have Inversion of Control when Web API manage the request flow. Only...

**Comment by alexandrebeato** [comment]
I always thought that **dependency injection** was one way to implement **inversion of control**.

**Comment by alexandrebeato** [comment]
Solved in [https://github.com/alexandrebeato/bankflix/commit/c2a05924292cd6b0f8c6d9e551269b0cdd37777f](url)
